/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import Controller.OrdersController;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

public class AddOrders extends javax.swing.JFrame {

    /** Creates new form Orders */
    public AddOrders() {
        initComponents();
    }
    
    private String getSelectedDate() {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd"); // Set to yyyy-MM-dd format
        if (ODInput.getDate() != null) {
            return sdf.format(ODInput.getDate());
        } else {
            JOptionPane.showMessageDialog(this, "Please select a valid date.", "Error", JOptionPane.ERROR_MESSAGE);
            return null;
        }
    }

    
    private void sendDataToController() {
        // Get the values from the fields
        String orderID = orderIDInput.getText().trim();
        String customerName = customerNameInput.getText().trim();
        String product = ProductInput.getText();
        String quantity = QuantityInput.getText().trim();
        String price = PriceInput.getText().trim();
        String orderDate = getSelectedDate();

                

        // Check if any of the fields are blank
        if (orderID.isEmpty() || customerName.isEmpty() || product.isEmpty() 
                || quantity.isEmpty() || price.isEmpty() || orderDate.isEmpty()) {
            // Show an error message
            JOptionPane.showMessageDialog(null, "All fields must be filled out", "Input Error", JOptionPane.ERROR_MESSAGE);
        } else {
            // Send data to the controller
            OrdersController.Orders(orderID, customerName, product, 
                    quantity, price, orderDate);
        }
    }
    
    public void clearField() {
        orderIDInput.setText("");
        customerNameInput.setText("");
        ProductInput.setText("");
        QuantityInput.setText("");
        PriceInput.setText("");
        ODInput.setDate(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Topic = new javax.swing.JLabel();
        orderIDLabel = new javax.swing.JLabel();
        orderIDInput = new javax.swing.JTextField();
        OrderNameLable = new javax.swing.JLabel();
        customerNameInput = new javax.swing.JTextField();
        QuantityLabel = new javax.swing.JLabel();
        QuantityInput = new javax.swing.JTextField();
        ProductLable = new javax.swing.JLabel();
        OrderDateLable = new javax.swing.JLabel();
        addOrderBtn = new javax.swing.JButton();
        CloseBtn = new javax.swing.JLabel();
        ProductInput = new javax.swing.JTextField();
        ODInput = new com.toedter.calendar.JDateChooser();
        PriceInput = new javax.swing.JTextField();
        PriceLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Topic.setFont(new java.awt.Font("Dubai", 1, 22)); // NOI18N
        Topic.setForeground(new java.awt.Color(0, 102, 102));
        Topic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Topic.setText("Crochet Items Management System - Add Order");
        jPanel1.add(Topic, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 623, -1));

        orderIDLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        orderIDLabel.setText("Order ID ");
        jPanel1.add(orderIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, -1));
        jPanel1.add(orderIDInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 250, -1));

        OrderNameLable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        OrderNameLable.setText("Customer Name ");
        jPanel1.add(OrderNameLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, -1));

        customerNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNameInputActionPerformed(evt);
            }
        });
        jPanel1.add(customerNameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 250, -1));

        QuantityLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        QuantityLabel.setText("Quantity");
        jPanel1.add(QuantityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));
        jPanel1.add(QuantityInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 270, -1));

        ProductLable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ProductLable.setText("Product");
        jPanel1.add(ProductLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, -1));

        OrderDateLable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        OrderDateLable.setText("Order Date");
        jPanel1.add(OrderDateLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, -1, -1));

        addOrderBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addOrderBtn.setText("Place Order");
        addOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrderBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addOrderBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, -1, -1));

        CloseBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CloseBtn.setForeground(new java.awt.Color(153, 0, 0));
        CloseBtn.setText("X");
        CloseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseBtnMouseClicked(evt);
            }
        });
        jPanel1.add(CloseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, -1, 21));

        ProductInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductInputActionPerformed(evt);
            }
        });
        jPanel1.add(ProductInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 270, -1));

        ODInput.setDateFormatString("yyyy/MM/dd");
        jPanel1.add(ODInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 270, -1));
        jPanel1.add(PriceInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 270, -1));

        PriceLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PriceLabel.setText("Price (Rs.)");
        jPanel1.add(PriceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 80, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Bg-image1.jpeg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 700, 500));

        jMenuBar2.setBackground(new java.awt.Color(204, 204, 204));
        jMenuBar2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar2.setForeground(new java.awt.Color(0, 102, 102));

        jMenu3.setText("Bashi's boutique");
        jMenuBar2.add(jMenu3);
        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void customerNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerNameInputActionPerformed

    private void addOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrderBtnActionPerformed
        sendDataToController();
        clearField();
    }//GEN-LAST:event_addOrderBtnActionPerformed

    private void CloseBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseBtnMouseClicked
        dispose();
    }//GEN-LAST:event_CloseBtnMouseClicked

    private void ProductInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductInputActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddOrders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CloseBtn;
    private com.toedter.calendar.JDateChooser ODInput;
    private javax.swing.JLabel OrderDateLable;
    private javax.swing.JLabel OrderNameLable;
    private javax.swing.JTextField PriceInput;
    private javax.swing.JLabel PriceLabel;
    private javax.swing.JTextField ProductInput;
    private javax.swing.JLabel ProductLable;
    private javax.swing.JTextField QuantityInput;
    private javax.swing.JLabel QuantityLabel;
    private javax.swing.JLabel Topic;
    private javax.swing.JButton addOrderBtn;
    private javax.swing.JTextField customerNameInput;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField orderIDInput;
    private javax.swing.JLabel orderIDLabel;
    // End of variables declaration//GEN-END:variables

}
