/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.SuppliersController;
import Model.DBSearch;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class UpdateDeleteSuppliers extends javax.swing.JFrame {

    /**
     * Creates new form AddSupplier
     */
    
    private SuppliersController SuppliersController;

    private DBSearch dbSearch;
    
    public UpdateDeleteSuppliers() {
        initComponents();
        dbSearch = new DBSearch();

    }
    
    public void clearField() {
        supplierIdInput.setText("");
        supplierNameInput.setText("");
        contactNumberInput.setText("");
        emailInput.setText("");
        addressInput.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CloseBtn = new javax.swing.JLabel();
        getSupplierDataBtn = new javax.swing.JButton();
        DeleteSupplierBtn = new javax.swing.JButton();
        UpdateSupplierBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        supplierIdLable = new javax.swing.JLabel();
        supplierIdInput = new javax.swing.JTextField();
        supplierNameLable = new javax.swing.JLabel();
        supplierNameInput = new javax.swing.JTextField();
        contactNumberLable = new javax.swing.JLabel();
        contactNumberInput = new javax.swing.JTextField();
        emailLable = new javax.swing.JLabel();
        emailInput = new javax.swing.JTextField();
        phoneNumberLable = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressInput = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CloseBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CloseBtn.setForeground(new java.awt.Color(153, 51, 0));
        CloseBtn.setText("X");
        CloseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseBtnMouseClicked(evt);
            }
        });
        jPanel1.add(CloseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 13, -1, 21));

        getSupplierDataBtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        getSupplierDataBtn.setText("Get Data");
        getSupplierDataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getSupplierDataBtnActionPerformed(evt);
            }
        });
        jPanel1.add(getSupplierDataBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, -1, -1));

        DeleteSupplierBtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        DeleteSupplierBtn.setText("Delete Supplier Details");
        DeleteSupplierBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteSupplierBtnActionPerformed(evt);
            }
        });
        jPanel1.add(DeleteSupplierBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, -1, -1));

        UpdateSupplierBtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        UpdateSupplierBtn.setText("Update Supplier Details");
        UpdateSupplierBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateSupplierBtnActionPerformed(evt);
            }
        });
        jPanel1.add(UpdateSupplierBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 410, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dubai", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Crochet Items Management System - Update & Delete Supplier  ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 776, -1));

        supplierIdLable.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        supplierIdLable.setText("Supplier ID");
        jPanel1.add(supplierIdLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, -1));
        jPanel1.add(supplierIdInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 160, -1));

        supplierNameLable.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        supplierNameLable.setText("Supplier Name");
        jPanel1.add(supplierNameLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, -1, -1));

        supplierNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierNameInputActionPerformed(evt);
            }
        });
        jPanel1.add(supplierNameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 260, -1));

        contactNumberLable.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        contactNumberLable.setText("Conatct Number");
        jPanel1.add(contactNumberLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, -1, -1));

        contactNumberInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactNumberInputActionPerformed(evt);
            }
        });
        jPanel1.add(contactNumberInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 260, -1));

        emailLable.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        emailLable.setText("Email Address");
        jPanel1.add(emailLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, -1, -1));
        jPanel1.add(emailInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 260, -1));

        phoneNumberLable.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        phoneNumberLable.setText("Address");
        jPanel1.add(phoneNumberLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, -1, -1));

        addressInput.setColumns(20);
        addressInput.setRows(5);
        jScrollPane1.setViewportView(addressInput);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 270, -1));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Bg-image2.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 800, 500));

        jMenuBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jMenu1.setText("Bashi's boutique");
        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CloseBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseBtnMouseClicked
        dispose();
    }//GEN-LAST:event_CloseBtnMouseClicked

    private void getSupplierDataBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getSupplierDataBtnActionPerformed
        try {
            String SupplierID = supplierIdInput.getText().trim();

            if (SupplierID == null) {
                JOptionPane.showMessageDialog(this, "Please Type a memberID.", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }

            ResultSet resultSet = dbSearch.searchSupplierDetailsByID(SupplierID);

            if (resultSet != null && resultSet.next()) {
                supplierNameInput.setText(resultSet.getString("supplierName"));
                contactNumberInput.setText(resultSet.getString("contactNumber"));
                emailInput.setText(resultSet.getString("email"));
                addressInput.setText(resultSet.getString("address"));


            } else {
                JOptionPane.showMessageDialog(this, "No member found for the Typed SupplierID.", "No Data", JOptionPane.INFORMATION_MESSAGE);
            }

            if (resultSet != null && !resultSet.isClosed()) {
                resultSet.close();
            }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "An error occurred while searching for Suppliers.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_getSupplierDataBtnActionPerformed

    private void DeleteSupplierBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteSupplierBtnActionPerformed
        String suppierID = supplierIdInput.getText().trim();

        if (suppierID.isEmpty()) {
            JOptionPane.showMessageDialog(null, "suppliers suppierID must be filled out",
                "Input Error", JOptionPane.ERROR_MESSAGE);
        } else {
            // Confirm with the user before deleting
            int confirmation = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this supplier Details?",
                "Confirm Deletion", JOptionPane.YES_NO_OPTION);

            // If user confirms deletion
            if (confirmation == JOptionPane.YES_OPTION) {
                try {
                    boolean success = SuppliersController.deleteSuppier(suppierID);

                    if (success) {
                        JOptionPane.showMessageDialog(null, "Supplier Details deleted successfully",
                            "Deletion Successful", JOptionPane.INFORMATION_MESSAGE);
                        // Clear the input fields after successful deletion
                        clearField();
                    } else {
                        JOptionPane.showMessageDialog(null, "Failed to delete supplier",
                            "Deletion Failed", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (SQLException ex) {
                    ex.printStackTrace();
                    // Handle SQL exception
                    JOptionPane.showMessageDialog(null, "An error occurred while deleting Supplier",
                        "Deletion Failed", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_DeleteSupplierBtnActionPerformed

    private void UpdateSupplierBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateSupplierBtnActionPerformed

        String supplierID = supplierIdInput.getText().trim();
        String supplierName = supplierNameInput.getText().trim();
        String contactNumber = contactNumberInput.getText().trim();
        String email = emailInput.getText().trim();
        String address = addressInput.getText().trim();

        // Check if any of the fields are blank
        if (supplierID.isEmpty() || supplierName.isEmpty() || contactNumber.isEmpty() || 
                email.isEmpty() || address.isEmpty()) {
            // Show an error message
            JOptionPane.showMessageDialog(null, "All fields must be filled out", 
                    "Input Error", JOptionPane.ERROR_MESSAGE);
        } else {

            boolean success = false;
            success = SuppliersController.updateSuppier(supplierID, supplierName, contactNumber, email, address);
            if (success) {
                JOptionPane.showMessageDialog(null, "Supplier information updated successfully",
                    "Update Successful", JOptionPane.INFORMATION_MESSAGE);
                clearField();
            } else {
                JOptionPane.showMessageDialog(null, "Failed to update Supplier information",
                    "Update Failed", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_UpdateSupplierBtnActionPerformed

    private void supplierNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supplierNameInputActionPerformed

    private void contactNumberInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactNumberInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactNumberInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateDeleteSuppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateDeleteSuppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateDeleteSuppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateDeleteSuppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateDeleteSuppliers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CloseBtn;
    private javax.swing.JButton DeleteSupplierBtn;
    private javax.swing.JButton UpdateSupplierBtn;
    private javax.swing.JTextArea addressInput;
    private javax.swing.JTextField contactNumberInput;
    private javax.swing.JLabel contactNumberLable;
    private javax.swing.JTextField emailInput;
    private javax.swing.JLabel emailLable;
    private javax.swing.JButton getSupplierDataBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel phoneNumberLable;
    private javax.swing.JTextField supplierIdInput;
    private javax.swing.JLabel supplierIdLable;
    private javax.swing.JTextField supplierNameInput;
    private javax.swing.JLabel supplierNameLable;
    // End of variables declaration//GEN-END:variables
}
